default_platform(:android)

platform :android do
    desc "Lint"
    lane :lint do
        gradle(task: "lintDebug")
    end

    desc "Unit test"
    lane :unit_test do
        gradle(task: "testDebugUnitTest")
    end

    desc "Build release"
    lane :build_app do |options|
        build_android_app(
            task: ENV["BUILD_TASK"],
            build_type: ENV["BUILD_TYPE"],
            properties: {
                "android.injected.signing.store.file" => "/tmp/my-release-key.keystore",
                "android.injected.signing.store.password" => "#{ENV["KEYSTORE_PW"]}",
                "android.injected.signing.key.alias" => "#{ENV["ALIAS"]}",
                "android.injected.signing.key.password" => "#{ENV["ALIAS_PW"]}",
                "versionCode" => ENV["CI_PIPELINE_ID"],
            }
        )
    end

    desc "Submit a new build to Github Releases"
    lane :github_release do |options|
        begin
            build_release()
            changes = changelog_from_git_commits(
                between: [ENV["CI_COMMIT_BEFORE_SHA"], "HEAD"],
                pretty: "- (%ae) %s",
                date_format: "short",
                match_lightweight_tag: false,
                merge_commit_filtering: "exclude_merges"
            )

            #puts "Uploading new version(#{ENV["CI_PIPELINE_ID"]}) to Firebase"

#             github_release = set_github_release(
#                 repository_name: "okuymakov/test-ci-cd",
#                 api_token: ENV["GITHUB_TOKEN"],
#                 name: "Release",
#                 tag_name: "v1.22.0",
#                 description: changes,
#                 commitish: "master",
#                 upload_assets: ["release/gplay-release-" + options["versionCode"] + ".apk"]
#             )

#             firebase_app_distribution(
#                 app: ENV["FIREBASE_APP_ID"],
#                 groups: ENV["FIREBASE_TESTER_GROUP_NAME"],
#                 android_artifact_type: ENV["FIREBASE_ARTIFACT_TYPE"] = "APK",
#                 service_credentials_file: "./key_firebase.json",
#                 release_notes: changes,
#                 debug: true,
#             )
            success("Github Release")
        rescue  => exception
            UI.user_error!(exception)
        end
    end

