default_platform(:android)

platform :android do
    desc "Lint"
    lane :lint do
        gradle(task: "lintDebug")
    end

    desc "Unit test"
    lane :unit_test do
        gradle(task: "testDebugUnitTest")
    end

    desc "Build with signature"
    lane :build_signed do |options|
        build_android_app(
            task: options[:build_task],
            build_type: options[:build_type],
            properties: {
                "android.injected.signing.store.file" => "/tmp/my-release-key.keystore",
                "android.injected.signing.store.password" => "#{ENV["KEYSTORE_PW"]}",
                "android.injected.signing.key.alias" => "#{ENV["ALIAS"]}",
                "android.injected.signing.key.password" => "#{ENV["ALIAS_PW"]}",
                "versionCode" => ENV["VERSION_CODE"],
                "versionName" => ENV["VERSION_NAME"],
            }
        )
    end

    desc "Upload to Github Releases"
    lane :github_release do |options|
        begin
            build_signed(build_task: "assemble", build_type: "Release")
            build_signed(build_task: "bundle", build_type: "Release")

            changes = changelog_from_git_commits(
                between: [ENV["CI_COMMIT_BEFORE_SHA"], "HEAD"],
                pretty: "- (%ae) %s",
                date_format: "short",
                match_lightweight_tag: false,
                merge_commit_filtering: "exclude_merges"
            )

            set_github_release(
                repository_name: "okuymakov/test-ci-cd",
                api_bearer: ENV["GITHUB_TOKEN"],
                name: "CiCdApp #{ENV["VERSION_NAME"]}.#{ENV["CI_PIPELINE_ID"]}",
                tag_name: "v#{ENV["VERSION_NAME"]}.#{ENV["CI_PIPELINE_ID"]}",
                description: changes,
                commitish: "master",
                upload_assets: [
                    "app/build/outputs/apk/release/app-release.apk",
                    "app/build/outputs/bundle/release/app-release.aab"
                ]
            )
        rescue  => exception
            UI.user_error!(exception)
        end
    end
end
