name: Push CD

on:
  push:
    branches: master
env:
  KEYSTORE_PW: ${{ secrets.KEYSTORE_PW }}
  KEYSTORE: ${{ secrets.KEYSTORE }}
  ALIAS: ${{ secrets.ALIAS }}
  ALIAS_PW: ${{ secrets.ALIAS_PW }}
  CI_PIPELINE_ID: ${{ github.run_number }}
  CI_COMMIT_BEFORE_SHA: ${{ github.event.before }}
  CI_ENVIRONMENT_NAME: ${{ github.workflow }}

jobs:
  build_release:
    name: Build Release AAB and APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6'
      - name: Install bundler
          run: |
            gem install bundler:2.2.27
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3

      - run: |
          bundle exec fastlane github_release
        env:
          BUILD_TASK: "assemble"
          BUILD_TYPE: "release"
