name: Push CD

on:
  push:
    branches: master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_PW: ${{ secrets.KEYSTORE_PW }}
  KEYSTORE: ${{ secrets.KEYSTORE }}
  ALIAS: ${{ secrets.ALIAS }}
  ALIAS_PW: ${{ secrets.ALIAS_PW }}
  CI_PIPELINE_ID: ${{ github.run_number }}
  CI_COMMIT_BEFORE_SHA: ${{ github.event.before }}
  CI_ENVIRONMENT_NAME: ${{ github.workflow }}

jobs:
  build_release:
    name: Build Release AAB and APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 'Extract version'
        id: vars
        run: |
          export $(cat .github/workflows/version.env | xargs)
          echo "version_code=${VERSION_CODE}" >> $GITHUB_OUTPUT
          echo "version_name=${VERSION_NAME}" >> $GITHUB_OUTPUT
      - name: 'Upload to Github Releases'
        env:
          VERSION_CODE: ${{ steps.vars.outputs.version_code }}
          VERSION_NAME: ${{ steps.vars.outputs.version_name }}
        run: |
          echo $KEYSTORE | base64 -d -i > /tmp/my-release-key.keystore
          fastlane github_release
        
