name: Push CD

on:
  push:
    branches: master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_PW: ${{ secrets.KEYSTORE_PW }}
  KEYSTORE: ${{ secrets.KEYSTORE }}
  ALIAS: ${{ secrets.ALIAS }}
  ALIAS_PW: ${{ secrets.ALIAS_PW }}
  CI_PIPELINE_ID: ${{ github.run_number }}
  CI_COMMIT_BEFORE_SHA: ${{ github.event.before }}
  CI_ENVIRONMENT_NAME: ${{ github.workflow }}

jobs:
  build_release:
    name: Build Release AAB and APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: echo $GITHUB_TOKEN
      - run: |
          echo $KEYSTORE | base64 -d -i > /tmp/my-release-key.keystore
          fastlane github_release
        env:
          BUILD_TASK: "assemble"
          BUILD_TYPE: "release"
